{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "f3e87673-97b8-4ed0-a253-dd115c434d14",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here are ten unique, professional, and properly formatted full names:', 'Emily J. Patel', 'Julianne M. Rodriguez', 'Liam D. Reyes', 'Ava L. Jensen', 'Ethan R. Wallace', 'Sophia K. Brooks', 'Alexander G. Lee', 'Ruby N. Singh', 'Julian P. Martin', 'Charlotte E. Russell']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Emily Anne Patterson', 'Julianne Marie Rodriguez', 'Alexander Ryan Jensen', 'Ava Leigh Thompson', 'Ethan James Mitchell', 'Sophia Elizabeth Lee', 'Lucas Cole Martin', 'Isabella Rose Garcia', 'Benjamin Michael Patel', 'Hannah Claire Taylor']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Emily Anne Patterson', 'Julian Michael Santos', 'Sophia Rachel Lee', 'Alexander James Reed', 'Ava Elaine Martin', 'Ethan Christopher Brooks', 'Isabella Claire Reynolds', 'Benjamin Patrick Walsh', 'Charlotte Elizabeth Grant', 'Matthew Ryan Taylor']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Alexandra Rae Wilson', 'Ethan Michael Reyes', 'Sophia Isabella Garcia', 'Julianne Marie Thompson', 'Harrison Cole Jenkins', 'Ava Elizabeth Lee', 'Lucas Patrick Brooks', 'Maya Danielle Patel', 'Benjamin Joseph Kim', 'Charlotte Elizabeth Sawyer']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Alexander Ryan Thompson', 'Sophia Elizabeth Patel', 'Julian Michael Reyes', 'Ava Leigh Chen', 'Maya Ruby Singh', 'Julianne Isabella Garcia', \"Liam Patrick O'Connor\", 'Charlotte Danielle Kim', 'Harrison James Sawyer']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Emily Anne Thompson', 'Ethan James Russell', 'Ava Elizabeth Patel', 'Julian Christopher Lee', 'Sophia Isabella Garcia', 'Alexander Ryan Mitchell', 'Lauren Nicole Jenkins', 'Christopher Michael Santos', 'Abigail Rose Hernandez', 'Jackson William Taylor']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Alexandra Nicole Thompson', 'Julian Edward Blackwood', 'Sophia Rachel Patel', 'Ethan Michael Santos', 'Emily Anne Lee', 'Gabriel Lucas Brooks', 'Charlotte Elizabeth Martin', 'Harrison James Reed', 'Ava Elizabeth Rodriguez', 'Caleb Alexander Wallace']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list:', 'Alexandra Joy Reynolds', 'Ethan Michael Thompson', 'Maya Elise Patel', 'Julianne Nicole Russo', 'Caleb Alexander Lee', 'Ava Isabella Garcia', 'Liam Christopher Brooks', 'Sophia Elizabeth Martin', 'Jackson Cole Jenkins', 'Emily Claire Wilson']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Maya Elizabeth Thompson', 'Ethan Alexander Reed', 'Ava Leigh Martin', 'Julian Michael Santos', 'Sophia Isabella Patel', 'Liam Christopher Brooks', 'Charlotte Elizabeth Russell', 'Jackson Cole Mitchell', 'Emily Rachel Lee', 'Benjamin Tyler Jenkins']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Emily J. Lee', 'Jackson Reed Taylor', 'Ava Marie Jenkins', 'Ethan A. Patel', 'Sophia Elizabeth Brown', 'Logan Matthew Brooks', 'Maya Rose Sanchez', 'Alexander Ryan Cole', 'Charlotte Anne Martin', 'Julian Michael Harris']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of names:', 'Olivia Paige Thompson', 'Ava Elizabeth Martinez', 'Julian Michael Santos', 'Emily Rose Hernandez', 'Logan Christopher Brooks', 'Sophia Isabella Patel', 'Alexander Ryan Mitchell', \"Charlotte Maeve O'Connor\", 'Gabriel Benjamin Lee']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Emily Anne Rodriguez', 'Julianne Marie Thompson', 'Alexander Ryan Patel', 'Ethan James Reed', 'Sophia Isabella Garcia', 'Benjamin Cole Martin', 'Charlotte Mae Sawyer', 'Logan Thomas Brooks', 'Alexandra Rose Hernandez']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Julian Alexander Reyes', 'Ava Elizabeth Patel', 'Ethan Michael Reed', 'Sophia Isabella Garcia', 'Liam Christopher Lee', 'Madison Avery Martin', 'Jackson Cole Brooks', 'Charlotte Elizabeth Davis', 'Benjamin Ryan Jenkins']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Julian Michael Reyes', 'Ethan James Mitchell', 'Sofia Maria Rodriguez', 'Alexander Cole Brooks', 'Isabella Rose Garcia', 'Jackson Ryan Jenkins', 'Charlotte Elizabeth Patel', 'Benjamin Tyler Wallace']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Alexandra Rae Thompson', 'Julian Alexander Pierce', 'Maya Elianore Quasar', 'Ethan Michael Reyes', 'Sophia Isabella Jenkins', 'Liam Christopher Mitchell', 'Charlotte Elizabeth Morgan', 'Jackson Reed Alvarez', 'Ava Elizabeth Russell', 'Lucas James Sawyer']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Emily J. Patel', 'Julian S. Reed', 'Aiden Michael Ryan', 'Sofia Maria Garcia', 'Ethan Thomas Brown', 'Liam Christopher Hall', 'Ruby Rose Sanchez', 'Alexander James Martin', 'Abigail Paige Davis']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Ava Elizabeth Martin', 'Ethan Michael Thompson', 'Lila Isabella Garcia', 'Julian Alexander Patel', 'Sophia Rachel Lee', 'Caleb James Reynolds', 'Emily Claire Johnson', 'Alexander Ryan Mitchell', 'Charlotte Elizabeth Brown', 'Harrison Christopher Hall']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Avery Elizabeth Thompson', 'Ethan Sebastian Michaels', 'Olivia Rose Jenkins', 'Julian Alexander Pierce', 'Ava Marie Sanchez', 'Lucas Ryan Walker', 'Emily Claire Patel', 'Alexander Cole Harris', 'Sophia Isabella Garcia', 'Jackson Reed Foster']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Ethan James Reed', 'Ava Elizabeth Patel', 'Julian Sebastian Martinez', 'Madison Paige Reynolds', 'Alexander Ryan Chen', 'Charlotte Rose Johnson', 'Benjamin Michael Santos', 'Sophia Isabella Garcia', 'Harrison William Lee']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Alexandra Renee Thompson', 'Ethan James Parker', 'Maya Leilani Singh', 'Julianne Elise Martin', 'Benjamin Charles Lee', 'Sofia Isabella Garcia', 'Lucas Alexander Rodriguez', 'Ava Elizabeth Jenkins', 'Gabriel Michael Hall', 'Emily Anne Patel']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Emily Rachel Thompson', 'Julian Michael Patel', 'Ava Elizabeth Brown', 'Ethan James Reed', 'Sofia Marie Garcia', 'Alexander Ryan Lee', 'Mia Isabella Rodriguez', 'Benjamin Cooper Martin', 'Charlotte Elizabeth Wright', 'Logan Christopher Brooks']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Emily Anne Wilson', 'Julian Michael Reed', 'Ava Elizabeth Patel', 'Ethan James Douglas', 'Sophia Rachel Lee', 'Alexander Cole Martin', 'Isabella Marie Garcia', 'Christopher Thomas Brown', 'Gabriella Sophia Rodriguez', 'William Anthony Jenkins']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional, and properly formatted full names:', 'Emily J. Thompson', 'Alexander R. Patel', 'Sophia A. Rodriguez', 'Ethan M. Lee', 'Ava M. Hernandez', 'Lucas J. Brown', 'Isabella G. Martin', 'Julian S. Kim', 'Charlotte E. Taylor', 'Gabriel D. Santos']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Paige Reynolds', 'Julianne Marie Thompson', 'Ethan Jameson Brooks', 'Sofia Elise Rodriguez', 'Harrison Lucas Wallace', 'Ava Elizabeth Martin', 'Lucas Alexander Pierce', 'Maisie Claire Jenkins', 'Benjamin Cole Fletcher', 'Evelyn Ruby Kennedy']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Ethan James Parker', 'Ava Elizabeth Russell', 'Julian Michael Santos', 'Sophia Isabelle Martin', 'Madison Paige Reynolds', 'Benjamin Tyler Nelson', 'Charlotte Rose Wallace', 'Harrison Grayson Jenkins']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander Ryan Thompson', 'Maya Elizabeth Rodriguez', 'Ethan James Lee', 'Sophia Isabella Patel', 'Julian Robert Sanchez', 'Ava Leigh Foster', 'Liam Christopher Jensen', 'Emily Anne Walton', 'Caleb Michael Reynolds', 'Abigail Rose Whitaker']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julian Michael Reyes', 'Ethan James Mitchell', 'Sophia Isabella Garcia', 'Alexander Ryan Brooks', 'Charlotte Paige Russell', 'Lucas Christopher Jenkins', 'Maya Rose Nguyen', 'Benjamin Tyler Patel']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily Anne Taylor', 'Julianne Marie Lee', 'Alexander Ryan Foster', 'Ava Elizabeth Patel', 'Ethan James Reed', 'Maya Sophia Jensen', 'Lucas Michael Brooks', 'Gabriella Rose Rodriguez', 'Caleb David Russell', 'Sydney Nicole Marin']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Rae Thompson', 'Julian Alexander Brown', 'Sophia Elizabeth Rodriguez', 'Ethan Michael Lee', 'Ava Victoria Patel', 'Liam Christopher Martin', 'Isabella Rose Garcia', 'Julianne Marie Jenkins', 'Harrison Cole Simmons', 'Emily Claire Reynolds']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julian Michael Santos', 'Ava Elizabeth Rodriguez', 'Ethan James Patterson', 'Sofia Maria Garcia', 'Liam Christopher Brooks', 'Charlotte Rose Jenkins', 'Alexander Ryan Mitchell', 'Isabella Danielle Lee', 'Jackson Cole Simmons']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique, professional-sounding full names:', 'Alexandra Rose Jenkins', 'Ethan Michael Patel', 'Ava Elizabeth Martinez', 'Julianne Marie Thompson', 'Lucas Ryan Hall', 'Sophia Isabella Garcia', 'Benjamin Russell Lee', 'Charlotte Ann Taylor', 'Gabriel Christopher Brooks', 'Madison Paige Reynolds']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emma Louise Thompson', 'Alexander Ryan Jenkins', 'Ava Marie Sanchez', 'Ethan Michael Patel', 'Sophia Isabella Russell', 'Julianne Elizabeth Brown', 'Gabriel Christopher Lee', 'Isabella Claire Martin', 'Jackson Ryan Walker', 'Madison Avery Wilson']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julian Alexander Reyes', 'Ethan Michael Patel', 'Sophia Isabella Garcia', 'Maya Rose Jensen', 'Julianne Marie Russell', 'Christopher James Martin', 'Gabriella Victoria Santos']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander James Mitchell', 'Ava Elizabeth Russell', 'Ethan Michael Thompson', 'Sophia Isabella Garcia', 'Julian Sebastian Lee', 'Emily Rose Patel', 'Benjamin Patrick Reynolds', 'Charlotte Victoria Wong', 'Harrison Tyler Brown', 'Madison Paige Martin']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julianne Elizabeth Brown', 'Alexander Ryan Jenkins', 'Sophia Mae Rodriguez', 'Benjamin Charles Patel', 'Ava Leigh Martin', 'Ethan James Reed', 'Charlotte Elizabeth Lee', 'Liam Michael Walsh', 'Hannah Rose Garcia']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Paige Reynolds', 'Julianne Marie Thompson', 'Ethan Alexander Wallace', 'Maya Elise Chen', 'Harrison James Russell', 'Lucas Tyler Martin', 'Benjamin Thomas Hall', 'Sophia Isabella Santos']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily J. Patel', 'Julian S. Rodriguez', 'Ava R. Lee', 'Liam M. Chen', 'Sophia E. Hernandez', 'Ethan A. Brooks', 'Charlotte G. Taylor', 'Jackson D. Russell', 'Olivia C. Nguyen', 'Alexander J. Moreno']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Ava Elizabeth Thompson', 'Sophia Rachel Patel', 'Julian Michael Santos', 'Emily Anne Taylor', 'Liam Christopher Brooks', 'Charlotte Elizabeth Brown', 'Benjamin Michael Martin', 'Isabella Claire Jenkins', 'Alexander James Lee']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julian Xavier Reyes', 'Ava Elizabeth Martin', 'Ethan Alexander Lee', 'Sydney Maeve Patel', 'Liam Michael Chen', 'Charlotte Rose Jenkins', 'Abigail Leigh Russell', 'Gabriel Nathaniel Santos']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here are 10 unique, professional, and properly formatted full names:', 'Alexander Ryan Thompson', 'Emma Louise Hernandez', 'Julian Christopher Lee', 'Ava Elisabeth Patel', 'Sophia Isabella Garcia', \"Liam Patrick O'Connor\", 'Benjamin Taylor Martin', 'Gabriella Marie Sanchez']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Elizabeth Jenkins', 'Julianne Marie Thompson', 'Ethan Alexander Brown', 'Sophia Rachel Patel', 'Benjamin Cole Martin', 'Olivia Claire Lee', 'Jackson Ryan Walker', 'Ava Elizabeth Garcia', 'Julian David Santos', 'Gabriella Sophia Rodriguez']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here are 10 unique, professional, and properly formatted full names:', 'Emily J. Thompson', 'Julian S. Lee', 'Ava R. Patel', 'Ethan M. Rodriguez', 'Liana K. Jensen', 'Caleb T. Martin', 'Ruby G. Singh', 'Alexander G. Brown', 'Sophia C. Hernandez', 'Logan D. Wallace']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Joy Thompson', 'Sophia Rachel Patel', 'Julianne Elizabeth Santos', 'Liam Christopher Lee', 'Jackson Ryan Mitchell', 'Maya Leila Jensen', 'Gabriel Dominic Pierce', 'Charlotte Elizabeth Martin']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Paige Reynolds', 'Ethan James Fletcher', 'Sofia Elena Vasquez', 'Julian Michael Santos', 'Ava Elizabeth Morrow', 'Liam Christopher Brooks', 'Maya Nicole Patel', 'Lucas Benjamin Russell', 'Gabriella Rose Garcia', 'Caleb Alexander Webb']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 unique full names:', 'Alexandra Elizabeth Jenkins', 'Julian Edward Blackwood', 'Sofia Isabelle Rodriguez', 'Ethan James Mitchell', 'Ava Lily Patel', 'Maya Rose Nguyen', 'Caleb Alexander Brooks', 'Emily Claire Kennedy', 'Jackson Ryan Thompson']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julianne Marie Patel', 'Alexander Ryan Cole', 'Sophia Elizabeth Lee', 'Charlotte Anne Russell', 'David Christopher Martin', 'Ava Elizabeth Santos', 'Harrison James Fraser', 'Julia Kate Warren']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julianne Elizabeth Taylor', 'Ethan Ryan Foster', 'Ava Leigh Carson', 'Alexander Cole Harrison', 'Sophia Maeve Patel', 'Julian Michael Santos', 'Emilia Rose Garcia', 'Liam Christopher Brooks', 'Charlotte Elizabeth Russell', 'Benjamin Tyler Jensen']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily J. Reynolds', 'Alexander W. Lawrence', 'Sofia M. Patel', 'Ethan T. Jackson', 'Ava L. Rodriguez', 'Julian S. Lee', 'Maya N. Brooks', 'Caleb A. Martin', 'Isabella K. Chen', 'Lucas R. Hernandez']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander R. Patel', 'Ava L. Reynolds', 'Ethan M. Chen', 'Sophia G. Rodriguez', 'Julian S. Lee', 'Charlotte E. Martin', 'Benjamin T. Vasquez', 'Isabella K. Jenkins', 'Harrison W. Sawyer']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of full names:', 'Ava Elizabeth Thompson', 'Julian Alexander Martin', 'Sophia Isabella Rodriguez', 'Ethan James Wilson', 'Madison Paige Lee', 'Lucas Cole Jenkins', 'Emily Anne Patel', 'Logan Ryan Mitchell', 'Benjamin David Hall']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra R. Thompson', 'Ethan J. Lee', 'Sofia M. Patel', 'Julian S. Reyes', 'Ava L. Wong', 'Christopher T. Martin', 'Gabriella A. Garcia', 'Ryan P. Brooks', 'Maya R. Singh', 'Liam C. Hall']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Avery Elizabeth Thompson', 'Julianne Marie Rodriguez', 'Ethan Alexander Lee', 'Sophia Isabella Patel', 'Liam Christopher Martin', 'Jasmine Rachel Kim', 'Alexander Ryan Jenkins', 'Emily Claire Brown', 'Gabriel Michael Santos']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Joy Thompson', 'Ethan Russell Lee', 'Sofia Maria Rodriguez', 'Julian Sebastian Taylor', 'Ava Elizabeth Patel', 'Liam Christopher Brown', 'Emily Anne Jenkins', 'Jackson Ryan Mitchell', 'Maya Nicole Brooks', 'Christopher Michael Reynolds']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Paige Jenkins', 'Ethan Russell Thompson', 'Ava Elise Martinez', 'Julian Michael Santos', 'Isabella Rose Garcia', 'Liam Christopher Brooks', 'Maya Danielle Patel', 'Caleb Alexander Reed', 'Sofia Elena Rodriguez', 'Jackson Cole Martin']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julian Michael Reyes', 'Ava Elizabeth Patel', 'Ethan James Brooks', 'Sophia Claire Lee', 'Liam Christopher Davis', 'Charlotte Rose Garcia', 'Alexander Ryan Mitchell', 'Mia Isabella Santos', 'Benjamin Cole Jenkins']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of full names:', 'Emily J. Wilson', 'Julianne Marie Thompson', 'Ava L. Patel', 'Sadie Rose Garcia', 'Lucas Alexander Brown', 'Mia Isabella Sanchez', 'Caleb Ryan Lee', 'Olivia Paige Martin', 'Logan James Douglas']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is a list of 10 unique, professional, and properly formatted full names:', 'Aiden Ryan Thompson', 'Sophia Elizabeth Rodriguez', 'Ethan Alexander Lee', 'Maya Jensen Patel', 'Julian Michael Santos', 'Ava Marie Brooks', 'Liam Christopher Reynolds', 'Isabella Rose Moreno', \"Caleb Patrick O'Connor\", 'Julia Nicole Garcia']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander Jameson Brooks', 'Ava Elise Thompson', 'Ethan Russell Patel', 'Maya Isabella Reyes', 'Julian Sebastian Brown', 'Sophia Danielle Lee', 'Lucas William Chen', 'Charlotte Elizabeth Martin', 'Gabriel Michael Santos', 'Emily Claire Jenkins']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list:', 'Alexandra Joy Thompson', 'Ethan Michael Patel', 'Ava Elise Reynolds', 'Julianne Marie Sanchez', 'Liam Christopher Brooks', 'Sophia Rachel Lee', 'Caleb Ryan Mitchell', 'Samantha Anne Hernandez', 'Jackson Cole Weaver', 'Emily Claire Russell']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Ethan James Carter', 'Ava Marie Rodriguez', \"Liam Patrick O'Connor\", 'Alexander Ryan Thompson', 'Julianne Nicole Moreno', 'Benjamin Tyler Lee', 'Emily Claire Taylor', 'Caleb William Jenkins', 'Victoria Rose Garcia']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily Anne Foster', 'Julian Sebastian Patel', 'Ava Michelle Lee', 'Ethan James Reed', 'Sophia Elizabeth Brown', 'Liam Christopher Martin', 'Charlotte Rose Taylor', 'Benjamin Michael Kim', 'Julia Isabella Garcia', 'Alexander Ryan Santos']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Paige Reynolds', 'Julianne Elizabeth Martin', 'Ethan Alexander Jackson', 'Maya Jensen Ryder', 'Charlotte Rosemary Wellesley', 'Dominic Michael Santos', 'Ava Elizabeth Cortez', 'Julian Michael Nguyen', 'Emily Anne Calderon', 'Harrison James McCormick']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander Ryan Thompson', 'Sophia Elizabeth Jenkins', 'Ethan Michael Patel', 'Ava Isabella Rodriguez', 'Julian Christopher Lee', 'Emily Claire Wilson', 'Liam James Chen', 'Charlotte Maeve Douglas', 'Benjamin Franklin Reed', 'Gabriella Rosemarie Sanchez']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julian Michael Reyes', 'Ava Elise Patel', 'Ethan Alexander Lee', 'Sophia Isabella Garcia', 'Charlotte Elizabeth Hall', 'Benjamin Ryan Mitchell', 'Harper Rose Wilson', 'Logan Cole Jenkins']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Ethan Alexander Thompson', 'Aria Elise Martin', 'Julian Christopher Lee', 'Ruby Maeve Patel', 'Lucas Augustus Reed', 'Ava Elizabeth Wong', 'Caleb Nathaniel Brown', 'Lila Isabelle Garcia', 'Jasper Everett Sawyer', 'Sophia Victoria Jenkins']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list:', 'Ava Elizabeth Rodriguez', 'Ethan Alexander Thompson', 'Sophia Isabella Martin', 'Julian Michael Patel', 'Emily Rose Hernandez', 'Liam Christopher Jenkins', 'Charlotte Abigail Lee', 'Caleb Benjamin Walker', 'Maya Nicole Chen', 'Jackson Ryan Mitchell']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Ava Elizabeth Reynolds', 'Julian Alexander Thompson', 'Sophia Rachel Patel', 'Ethan Michael Santos', 'Maya Isabella Garcia', 'Alexander Ryan Mitchell', 'Emily Claire Jenkins', 'Jackson Tyler Wilson']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Rose Jenkins', 'Julian Stellan Patel', 'Evelyn Maeve Reynolds', 'Ava Elise Martin', 'Ethan Alexander Lee', 'Sophia Isabella Garcia', 'Jackson Cole Mitchell', 'Mia Adeline Rodriguez', 'Caleb Ryan Thompson']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Mae Thompson', 'Everett Reed Jenkins', 'Sophia Elise Rodriguez', 'Julianne Paige Martin', 'Emily Anne Mitchell', 'Benjamin Cole Wallace', 'Abigail Rose Garcia', 'Harrison Grant Taylor', 'Olivia Claire Sanchez']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Marie Thompson', 'Ethan James Reed', 'Julianne Rose Sanchez', 'Benjamin Cole Lawrence', 'Ava Leigh Jenkins', 'Lucas Ryan Mitchell', 'Evelyn Rachel Chen', 'Gabriel Michael Santos', 'Isabella Claire Wong']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julianne Elizabeth Reynolds', 'Alexander James Petrov', 'Ava Leigh Thompson', 'Ethan Russell Jenkins', 'Sophia Patricia Rodriguez', 'Emily Claire Martin', 'Jackson Tyler Brown', 'Abigail Rose Garcia', 'Benjamin Edward Sawyer']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of 10 full names:', 'Emily J. Reynolds', 'Ethan Michael Patel', 'Ava Elise Thompson', 'Sophia Elizabeth Garcia', 'Jackson Ryan Jenkins', 'Charlotte Anne Wilson', 'Alexander James Martin', 'Abigail Paige Russell', 'Benjamin Tyler Hall']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Adeline Paige Reynolds', 'Ethan James Fletcher', 'Sophia Isabella Martin', 'Alexander Ryan Thompson', 'Emily Claire Taylor', 'Julian Michael Santos', 'Benjamin Patrick Lee', 'Abigail Rae Morgan', 'Harrison Cole Jenkins']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily J. Rodriguez', 'Alexander M. Thompson', 'Ava L. Patel', 'Julian S. Lee', 'Maya R. Garcia', 'Ethan W. Jenkins', 'Sophia K. Kim', 'Caleb T. Brown', 'Isabella M. Santiago', 'Logan P. Martin']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of full names:', 'Alexander James Reynolds', 'Ethan Michael Santos', 'Ava Marie Rodriguez', 'Julianne Rose Montgomery', 'Emily Claire Thompson', 'Jackson Ryan Mitchell', 'Olivia Jade Garcia', 'Benjamin Cole Harrison']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Paige Reynolds', 'Julian Michael Santos', 'Emily Rose Flynn', 'Ethan Alexander Thompson', 'Sofia Isabella Garcia', 'Benjamin Cole Jenkins', 'Ava Elizabeth Patel', 'Maya Isabelle Rodriguez', 'Christopher James Lee']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julianne M. Patel', 'Alexander W. Lee', 'Ava R. Garcia', 'Ethan S. Kim', 'Sophia N. Rodriguez', 'Julian B. Hawkins', 'Maya L. Jensen', 'Christopher T. Brown', 'Gabriella E. Martin']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julian Michael Reyes', 'Ethan Christopher Brown', 'Sophia Danielle Patel', 'Liam Alexander Grant', 'Charlotte Maeve Taylor', 'Alexander Ryan Jenkins', 'Gabriella Isabella Garcia', 'Benjamin Cole Martin']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily J. Wilson', 'Alexander M. Patel', 'Ava L. Reed', 'Jackson R. Lee', 'Maya K. Jensen', 'Ethan T. Brooks', 'Sophia N. Martin', 'Lucas A. Sanchez', 'Charlotte E. Hall', 'Julian S. Russell']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily Anne Williamson', 'Liam Christopher Reynolds', 'Ava Elizabeth Santos', 'Ethan Alexander Jenkins', 'Sofia Isabella Martin', 'Julian Michael Patel', 'Charlotte Rose Taylor', 'Alexander Cole Russell', 'Maya Leila Hernandez']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander James Thompson', 'Emily Rachel Patel', 'Julianne Marie Sanchez', 'Ethan Michael Lee', 'Ava Elizabeth Gray', 'Liam Christopher Kim', 'Sophia Isabella Martin', 'Jackson Ryan Hall', 'Charlotte Victoria Brown', 'Gabriel Matthew Reyes']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Paige Wilson', 'Julianne Marie Jenkins', 'Ethan Christopher Lee', 'Ava Elizabeth Thompson', 'Liam Michael Reed', 'Sofia Rose Martinez', 'Gabriel Lucas Brooks', 'Harrison Cole Davis', 'Emily Anne Patterson']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julian Christopher Lee', 'Ava Elizabeth Patel', 'Sophia Rachel Kim', \"Liam Patrick O'Connor\", 'Charlotte Maeve Douglas', 'Alexander Cole Jackson', 'Isabella Victoria Santos', 'Benjamin Tyler Russell']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily J. Patel', 'Julian S. Lee', 'Ava M. Rodriguez', 'Ethan T. Brooks', 'Sofia G. Jensen', 'Liam C. Martin', 'Charlotte E. Garcia', 'Alexander D. Hall', 'Maya L. Singh', 'Benjamin R. Walton']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Ethan James Mitchell', 'Ava Elizabeth Rodriguez', 'Julianne Marie Lee', 'Christopher Michael Santos', 'Sophia Claire Patel', 'Benjamin David Kim', 'Gabriella Isabella Garcia', 'Lucas Alexander Brown', 'Emily Anne Taylor']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Ethan Alexander Thompson', 'Ava Elizabeth Jenkins', 'Julianne Marie Patel', 'Liam Christopher Reyes', 'Sophia Rachel Lee', 'Alexander James Mitchell', 'Maya Nicole Singh', 'Gabriel Michael Santos', 'Emily Anne Martin', 'Christopher Tyler Brooks']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list of full names:', 'Ava Elizabeth Sanchez', 'Julian Christopher Lee', 'Brianna Marie Patel', 'Lucas James Wallace', 'Sophia Isabella Garcia', 'Alexander Ryan Jenkins', 'Maya Nicole Taylor', 'Gabriel Austin Brooks']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily J. Patterson', 'Julianne A. Rodriguez', 'Ava L. Schneider', 'Ethan M. Brooks', 'Samantha K. Jenkins', 'Alexander C. Patel', 'Isabella G. Martin', 'Benjamin T. Lee', 'Charlotte E. Hall', 'Harrison R. Thompson']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander Ryan Jenkins', 'Ethan Michael Patel', 'Julianne Rae Santos', 'Caleb Thomas Bradley', 'Sophia Isabella Martin', 'Logan Alexander Douglas', 'Gabriella Rose Moreno']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander James Reed', 'Ethan Michael Thompson', 'Rachel Marie Lee', 'Julianne Claire Taylor', 'Liam Christopher Brooks', 'Emily Anne Hall', 'Benjamin David Kim', 'Olivia Rose Garcia', 'Gabriel Patrick Santos']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Nicole Thompson', 'Ethan Russell Patel', 'Julian Michael Lee', 'Sophia Isabella Reynolds', 'Mia Ruby Singh', 'Caleb Alexander Brown', 'Emily Anne Taylor', 'Jackson Cole Harrison']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Here is the list:', 'Alexander Ryan Thompson', 'Ethan Michael Jensen', 'Ava Leigh Warner', 'Julian Sebastian Garcia', 'Maya Rose Alvarez', 'Isabella Claire Russell', 'Harrison James Brooks', 'Emily Anne Moreno']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julianne Marie Santiago', 'Ethan Russell Patel', 'Samantha Joy Everett', 'Lucas Christopher Lee', 'Ava Elizabeth Moreno', 'Benjamin Thomas Reed', 'Mia Isabella Vasquez', 'Caleb Alexander Martin', 'Emily Claire Nguyen']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Paige Thompson', 'Ethan Michael Reynolds', 'Sofia Isabelle Jensen', \"Lucas Patrick O'Connor\", 'Julianne Marie Santos', 'Gabriel Anthony Brown', 'Charlotte Rose Jenkins', 'Benjamin David Lee', 'Emily Claire Rodriguez']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Emily Rachel Thompson', 'Alexander James Reed', 'Ava Isabella Garcia', 'Ethan Christopher Lee', 'Ruby Maeve Collins', 'Caleb Benjamin Kim', 'Lila Catherine Hall', 'Benjamin Harrison Douglas']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexandra Paige Reynolds', 'Ava Elizabeth Chen', 'Julian Alexander Grey', 'Kaia Elise Jensen', 'Liam Christopher Brooks', 'Samantha Rachel Patel', 'Logan Thomas Russell', 'Gabriel Miguel Morales']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Ava Marie Thompson', 'Ethan James Russell', 'Maya Elise Patel', 'Julian Alexander Brown', 'Alexander Cole Morgan', 'Charlotte Rose Wells', 'Julianne Nicole Santos', 'Benjamin Tyler Harris', 'Gabriella Isabelle Rodriguez']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander J. Peterson', 'Maya R. Saeed', 'Ethan W. Thompson', 'Ava L. Morales', 'Julian S. Lee', 'Sophia G. Patel', 'Liam T. Reyes', 'Charlotte E. Brown', 'Jackson R. Martin', 'Emily A. Kimball']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Alexander Grant Thompson', 'Maya Elise Rodriguez', 'Ethan Matthew Lee', 'Sofia Maria Jensen', 'Julianne Paige Reynolds', 'Benjamin Cole Harris', 'Emma Louise Nguyen', 'Liam Joseph Patel', 'Ava Elizabeth Santos', 'Logan Christopher Brooks']\n",
      "INFO:root:Generating random name...\n",
      "INFO:root:Unique names generated: ['Julian Edward Reynolds', 'Ava Elizabeth Brown', 'Ethan Christopher Lee', 'Maya Rachel Patel', 'Liam Alexander Gray', 'Charlotte Victoria Martin', 'Jackson Ryan Walker', 'Sophia Isabella Garcia', 'Benjamin Harrison White']\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data generated and saved to 'interview_transcripts_and_resumes.xlsx'\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from together import Together\n",
    "from time import time\n",
    "import random\n",
    "import logging\n",
    "\n",
    "# Set up logging\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "\n",
    "# Set the Together API key\n",
    "os.environ[\"TOGETHER_API_KEY\"] = \"98d2e0259cfb2875868e6a30a295ec2a2bd70e18c394437e8b2374cc0cac8339\"\n",
    "client = Together()\n",
    "\n",
    "# Define reasons for selection and rejection\n",
    "select_reasons = {\n",
    "    \"leadership\": \"Demonstrated strong leadership and teamwork skills.\",\n",
    "    \"quick learner\": \"Proven ability to learn quickly and adapt to new challenges.\",\n",
    "    \"analytical skills\": \"Strong analytical and critical thinking abilities.\",\n",
    "    \"technical proficiency\": \"Outstanding technical proficiency in relevant programming languages.\",\n",
    "    \"communication skills\": \"Excellent communication and interpersonal skills.\",\n",
    "    \"project management\": \"Experience with agile methodologies and project management.\",\n",
    "    \"innovative\": \"Innovative thinking and a proactive approach to problem-solving.\",\n",
    "    \"best practices\": \"Solid understanding of industry best practices and standards.\",\n",
    "    \"positive feedback\": \"Consistently positive performance feedback from previous roles.\",\n",
    "    \"continuous learning\": \"Demonstrated commitment to continuous learning and professional development.\"\n",
    "}\n",
    "\n",
    "reject_reasons = {\n",
    "    \"key technologies\": \"Inadequate experience with key technologies required for the role.\",\n",
    "    \"fundamental concepts\": \"Limited understanding of fundamental concepts in the field.\",\n",
    "    \"problem-solving\": \"Poor problem-solving skills and inability to handle complex tasks.\",\n",
    "    \"communication\": \"Ineffective communication skills and difficulty articulating thoughts.\",\n",
    "    \"enthusiasm\": \"Lack of enthusiasm and motivation for the position.\",\n",
    "    \"team conflicts\": \"Difficulty working in a team and managing conflicts.\",\n",
    "    \"reliability\": \"Inconsistent job performance and reliability issues.\",\n",
    "    \"qualification\": \"Failure to meet the minimum qualification criteria for the role.\",\n",
    "    \"negative feedback\": \"Negative feedback from previous employers or references.\",\n",
    "    \"professionalism\": \"Demonstrated lack of professionalism and work ethics.\"\n",
    "}\n",
    "\n",
    "# Define roles and job descriptions\n",
    "roles = [\n",
    "    \"Data Analyst\",\n",
    "    \"Data Scientist\",\n",
    "    \"Full Stack Developer\",\n",
    "    \"Cloud Engineer\",\n",
    "    \"Java Full Stack Developer\",\n",
    "    \"Python Full Stack Developer\",\n",
    "    \"UI/UX Designer\",\n",
    "    \"Product Manager\",\n",
    "    \"Cybersecurity Analyst\",\n",
    "    \"DevOps Engineer\",\n",
    "    \"Machine Learning Engineer\",\n",
    "    \"Mobile App Developer\",\n",
    "    \"Blockchain Developer\"\n",
    "]\n",
    "\n",
    "job_description_templates = {\n",
    "    \"Data Analyst\": [\n",
    "        \"Analyze complex datasets to generate actionable business insights.\",\n",
    "        \"Develop dashboards and reports to visualize key metrics for decision-making.\",\n",
    "        \"Collaborate with stakeholders to define data analysis requirements.\"\n",
    "    ],\n",
    "    \"Data Scientist\": [\n",
    "        \"Build predictive models using machine learning techniques.\",\n",
    "        \"Analyze structured and unstructured data to identify trends and patterns.\",\n",
    "        \"Develop scalable data pipelines to process large datasets efficiently.\"\n",
    "    ],\n",
    "    \"Full Stack Developer\": [\n",
    "        \"Develop and maintain scalable web applications with frontend and backend integration.\",\n",
    "        \"Collaborate with designers to implement responsive user interfaces.\",\n",
    "        \"Ensure application performance and optimize for speed and scalability.\"\n",
    "    ],\n",
    "    \"Cloud Engineer\": [\n",
    "        \"Design and implement cloud infrastructure solutions.\",\n",
    "        \"Monitor and manage cloud deployments to ensure high availability.\",\n",
    "        \"Optimize cloud resource usage to reduce costs while maintaining performance.\"\n",
    "    ],\n",
    "    \"Java Full Stack Developer\": [\n",
    "        \"Develop end-to-end solutions using Java for both frontend and backend.\",\n",
    "        \"Integrate third-party APIs and services to extend functionality.\",\n",
    "        \"Ensure application security and implement best coding practices.\"\n",
    "    ],\n",
    "    \"Python Full Stack Developer\": [\n",
    "        \"Build web applications using Python frameworks like Django or Flask.\",\n",
    "        \"Implement RESTful APIs for seamless frontend-backend communication.\",\n",
    "        \"Work on database design and optimization for scalable applications.\"\n",
    "    ],\n",
    "    \"UI/UX Designer\": [\n",
    "        \"Create intuitive user interfaces based on user research and testing.\",\n",
    "        \"Develop wireframes, prototypes, and design systems for consistency.\",\n",
    "        \"Collaborate with developers to ensure accurate implementation of designs.\"\n",
    "    ],\n",
    "    \"Product Manager\": [\n",
    "        \"Lead product strategy and roadmaps to meet business goals.\",\n",
    "        \"Collaborate with cross-functional teams to ensure product success.\",\n",
    "        \"Gather user feedback to guide product enhancements.\"\n",
    "    ],\n",
    "    \"Cybersecurity Analyst\": [\n",
    "        \"Monitor systems for security breaches and vulnerabilities.\",\n",
    "        \"Develop and implement security measures to protect company data.\",\n",
    "        \"Perform risk assessments and penetration testing regularly.\"\n",
    "    ],\n",
    "    \"DevOps Engineer\": [\n",
    "        \"Automate and streamline CI/CD pipelines.\",\n",
    "        \"Collaborate with development teams to improve deployment processes.\",\n",
    "        \"Ensure system reliability and scalability.\"\n",
    "    ],\n",
    "    \"Machine Learning Engineer\": [\n",
    "        \"Develop and deploy machine learning models for business applications.\",\n",
    "        \"Optimize models for performance and scalability.\",\n",
    "        \"Stay updated with the latest advancements in AI/ML.\"\n",
    "    ],\n",
    "    \"Mobile App Developer\": [\n",
    "        \"Design and develop mobile applications for iOS and Android platforms.\",\n",
    "        \"Ensure applications are responsive and user-friendly.\",\n",
    "        \"Collaborate with designers to implement engaging interfaces.\"\n",
    "    ],\n",
    "    \"Blockchain Developer\": [\n",
    "        \"Develop decentralized applications (dApps) using blockchain technology.\",\n",
    "        \"Write smart contracts and optimize blockchain protocols.\",\n",
    "        \"Stay informed about the latest developments in blockchain.\"\n",
    "    ]\n",
    "}\n",
    "\n",
    "# Function to generate text using Together API\n",
    "def generate_text(prompt):\n",
    "    try:\n",
    "        response = client.chat.completions.create(\n",
    "            model=\"meta-llama/Llama-Vision-Free\",\n",
    "            messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "        )\n",
    "        return response.choices[0].message.content.strip()\n",
    "    except Exception as e:\n",
    "        return f\"Error generating text: {e}\"\n",
    "\n",
    "# Function to generate random names using LLM\n",
    "def generate_random_name(used_names):\n",
    "    while True:\n",
    "        logging.info(\"Generating random name...\")\n",
    "        prompt = \"Generate a list of 10 unique, professional, and properly formatted full names, one per line.\"\n",
    "        names = generate_text(prompt)\n",
    "\n",
    "        cleaned_names = [\n",
    "            name.strip().split('. ', 1)[-1].strip('*').strip()\n",
    "            for name in names.splitlines() if name.strip()\n",
    "        ]\n",
    "\n",
    "        unique_names = [name for name in cleaned_names if name not in used_names]\n",
    "        logging.info(f\"Unique names generated: {unique_names}\")\n",
    "\n",
    "        if unique_names:\n",
    "            chosen_name = random.choice(unique_names)\n",
    "            used_names.add(chosen_name)\n",
    "            return chosen_name\n",
    "\n",
    "        logging.warning(\"No unique names generated, retrying...\")\n",
    "\n",
    "# Evaluate transcript against predefined reasons\n",
    "def evaluate_transcript(transcript):\n",
    "    for keyword in select_reasons:\n",
    "        if keyword in transcript.lower():\n",
    "            return \"Selected\", select_reasons[keyword]\n",
    "    for keyword in reject_reasons:\n",
    "        if keyword in transcript.lower():\n",
    "            return \"Rejected\", reject_reasons[keyword]\n",
    "    return \"Rejected\", reject_reasons[\"key technologies\"]\n",
    "\n",
    "# Clean unnecessary lines from transcripts and resumes\n",
    "def clean_text(text, exclusions):\n",
    "    lines = text.splitlines()\n",
    "    clean_lines = [line for line in lines if not any(line.lower().startswith(exclusion) for exclusion in exclusions)]\n",
    "    return \"\\n\".join(clean_lines)\n",
    "\n",
    "# Data structure to store results\n",
    "data = {\n",
    "    'ID': [],\n",
    "    'Name': [],\n",
    "    'Role': [],\n",
    "    'Transcript': [],\n",
    "    'Resume': [],\n",
    "    'Decision': [],\n",
    "    'Reason for decision': [],\n",
    "    'Job Description': []\n",
    "}\n",
    "\n",
    "used_names = set()\n",
    "\n",
    "# Generate data for multiple candidates\n",
    "num_candidates = 100  # Change this to the desired number of candidates\n",
    "start_time = time()\n",
    "for i in range(1, num_candidates + 1):\n",
    "    candidate_name = generate_random_name(used_names)\n",
    "    while not candidate_name:\n",
    "        candidate_name = generate_random_name(used_names)\n",
    "\n",
    "    role = np.random.choice(roles)\n",
    "    job_description = np.random.choice(job_description_templates[role])\n",
    "\n",
    "    transcript_prompt = f\"\"\"\n",
    "    Generate a professional interview transcript between an interviewer and a candidate named {candidate_name}, applying for the role of {role}.\n",
    "    Keep the transcript professional, role-specific, and concise.\n",
    "    \"\"\"\n",
    "    transcript = generate_text(transcript_prompt)\n",
    "    cleaned_transcript = clean_text(transcript, [\"reason for decision:\"])\n",
    "\n",
    "    resume_prompt = f\"\"\"\n",
    "    Generate a resume for {candidate_name}, a {role}, applying for a role at a tech company.\n",
    "    Ensure the resume highlights relevant skills and experience concisely.\n",
    "    \"\"\"\n",
    "    resume = generate_text(resume_prompt)\n",
    "    cleaned_resume = clean_text(resume, [\"here\", \"here's\"])\n",
    "\n",
    "    decision, reason = evaluate_transcript(cleaned_transcript)\n",
    "\n",
    "    # Append data\n",
    "    data['ID'].append(f\"Rishi{i:03d}\")\n",
    "    data['Name'].append(candidate_name)\n",
    "    data['Role'].append(role)\n",
    "    data['Transcript'].append(cleaned_transcript)\n",
    "    data['Resume'].append(cleaned_resume)\n",
    "    data['Decision'].append(decision)\n",
    "    data['Reason for decision'].append(reason)\n",
    "    data['Job Description'].append(job_description)\n",
    "\n",
    "# Save results to Excel\n",
    "output_file = 'interview_transcripts_and_resumes.xlsx'\n",
    "df = pd.DataFrame(data)\n",
    "df.to_excel(output_file, index=False)\n",
    "print(f\"Data generated and saved to '{output_file}'\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "04c7fbf1-fdcf-4e9b-bef8-22c7d7c715e6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ID</th>\n",
       "      <th>Name</th>\n",
       "      <th>Role</th>\n",
       "      <th>Transcript</th>\n",
       "      <th>Resume</th>\n",
       "      <th>Decision</th>\n",
       "      <th>Reason for decision</th>\n",
       "      <th>Job Description</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Rishi001</td>\n",
       "      <td>Ruby N. Singh</td>\n",
       "      <td>Python Full Stack Developer</td>\n",
       "      <td>**Interview Transcript**\\n\\n**Interviewer:** R...</td>\n",
       "      <td>\\n**Ruby N. Singh**\\n**Contact Information:**\\...</td>\n",
       "      <td>Selected</td>\n",
       "      <td>Demonstrated commitment to continuous learning...</td>\n",
       "      <td>Implement RESTful APIs for seamless frontend-b...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Rishi002</td>\n",
       "      <td>Benjamin Michael Patel</td>\n",
       "      <td>Data Analyst</td>\n",
       "      <td>Here is a professional interview transcript be...</td>\n",
       "      <td>\\n**Benjamin Michael Patel**\\n**Contact Inform...</td>\n",
       "      <td>Selected</td>\n",
       "      <td>Demonstrated commitment to continuous learning...</td>\n",
       "      <td>Analyze complex datasets to generate actionabl...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Rishi003</td>\n",
       "      <td>Ethan Christopher Brooks</td>\n",
       "      <td>UI/UX Designer</td>\n",
       "      <td>**Interview Transcript: Ethan Christopher Broo...</td>\n",
       "      <td>\\n**Ethan Christopher Brooks**\\n**UI/UX Design...</td>\n",
       "      <td>Selected</td>\n",
       "      <td>Experience with agile methodologies and projec...</td>\n",
       "      <td>Create intuitive user interfaces based on user...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Rishi004</td>\n",
       "      <td>Ava Elizabeth Lee</td>\n",
       "      <td>Python Full Stack Developer</td>\n",
       "      <td>Here is a professional interview transcript be...</td>\n",
       "      <td>\\n**Ava Elizabeth Lee**\\n**Python Full Stack D...</td>\n",
       "      <td>Selected</td>\n",
       "      <td>Solid understanding of industry best practices...</td>\n",
       "      <td>Implement RESTful APIs for seamless frontend-b...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Rishi005</td>\n",
       "      <td>Sophia Elizabeth Patel</td>\n",
       "      <td>Machine Learning Engineer</td>\n",
       "      <td>**Interview Transcript**\\n\\n**Interviewer:** D...</td>\n",
       "      <td>\\n**Sophia Elizabeth Patel**\\n**Machine Learni...</td>\n",
       "      <td>Selected</td>\n",
       "      <td>Innovative thinking and a proactive approach t...</td>\n",
       "      <td>Optimize models for performance and scalability.</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>95</th>\n",
       "      <td>Rishi096</td>\n",
       "      <td>Alexandra Paige Reynolds</td>\n",
       "      <td>Data Analyst</td>\n",
       "      <td>**Interview Transcript: Alexandra Paige Reynol...</td>\n",
       "      <td>\\n**Alexandra Paige Reynolds**\\n**Contact Info...</td>\n",
       "      <td>Selected</td>\n",
       "      <td>Demonstrated strong leadership and teamwork sk...</td>\n",
       "      <td>Develop dashboards and reports to visualize ke...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96</th>\n",
       "      <td>Rishi097</td>\n",
       "      <td>Gabriella Isabelle Rodriguez</td>\n",
       "      <td>UI/UX Designer</td>\n",
       "      <td>**Interview Transcript**\\n\\n**Interviewer:** A...</td>\n",
       "      <td>\\n**Gabriella Isabelle Rodriguez**\\n**Contact ...</td>\n",
       "      <td>Selected</td>\n",
       "      <td>Demonstrated commitment to continuous learning...</td>\n",
       "      <td>Create intuitive user interfaces based on user...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>97</th>\n",
       "      <td>Rishi098</td>\n",
       "      <td>Charlotte E. Brown</td>\n",
       "      <td>Machine Learning Engineer</td>\n",
       "      <td>Here is a professional interview transcript be...</td>\n",
       "      <td>\\n**Charlotte E. Brown**\\n**Contact Informatio...</td>\n",
       "      <td>Rejected</td>\n",
       "      <td>Inadequate experience with key technologies re...</td>\n",
       "      <td>Develop and deploy machine learning models for...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>98</th>\n",
       "      <td>Rishi099</td>\n",
       "      <td>Liam Joseph Patel</td>\n",
       "      <td>Cloud Engineer</td>\n",
       "      <td>Here is a professional interview transcript be...</td>\n",
       "      <td>\\n**Liam Joseph Patel**\\n**Contact Information...</td>\n",
       "      <td>Selected</td>\n",
       "      <td>Solid understanding of industry best practices...</td>\n",
       "      <td>Monitor and manage cloud deployments to ensure...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>99</th>\n",
       "      <td>Rishi100</td>\n",
       "      <td>Maya Rachel Patel</td>\n",
       "      <td>Machine Learning Engineer</td>\n",
       "      <td>**Interview Transcript**\\n\\n**Interviewer:** D...</td>\n",
       "      <td>\\n**Maya Rachel Patel**\\n**Contact Information...</td>\n",
       "      <td>Selected</td>\n",
       "      <td>Innovative thinking and a proactive approach t...</td>\n",
       "      <td>Optimize models for performance and scalability.</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>100 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          ID                          Name                         Role  \\\n",
       "0   Rishi001                 Ruby N. Singh  Python Full Stack Developer   \n",
       "1   Rishi002        Benjamin Michael Patel                 Data Analyst   \n",
       "2   Rishi003      Ethan Christopher Brooks               UI/UX Designer   \n",
       "3   Rishi004             Ava Elizabeth Lee  Python Full Stack Developer   \n",
       "4   Rishi005        Sophia Elizabeth Patel    Machine Learning Engineer   \n",
       "..       ...                           ...                          ...   \n",
       "95  Rishi096      Alexandra Paige Reynolds                 Data Analyst   \n",
       "96  Rishi097  Gabriella Isabelle Rodriguez               UI/UX Designer   \n",
       "97  Rishi098            Charlotte E. Brown    Machine Learning Engineer   \n",
       "98  Rishi099             Liam Joseph Patel               Cloud Engineer   \n",
       "99  Rishi100             Maya Rachel Patel    Machine Learning Engineer   \n",
       "\n",
       "                                           Transcript  \\\n",
       "0   **Interview Transcript**\\n\\n**Interviewer:** R...   \n",
       "1   Here is a professional interview transcript be...   \n",
       "2   **Interview Transcript: Ethan Christopher Broo...   \n",
       "3   Here is a professional interview transcript be...   \n",
       "4   **Interview Transcript**\\n\\n**Interviewer:** D...   \n",
       "..                                                ...   \n",
       "95  **Interview Transcript: Alexandra Paige Reynol...   \n",
       "96  **Interview Transcript**\\n\\n**Interviewer:** A...   \n",
       "97  Here is a professional interview transcript be...   \n",
       "98  Here is a professional interview transcript be...   \n",
       "99  **Interview Transcript**\\n\\n**Interviewer:** D...   \n",
       "\n",
       "                                               Resume  Decision  \\\n",
       "0   \\n**Ruby N. Singh**\\n**Contact Information:**\\...  Selected   \n",
       "1   \\n**Benjamin Michael Patel**\\n**Contact Inform...  Selected   \n",
       "2   \\n**Ethan Christopher Brooks**\\n**UI/UX Design...  Selected   \n",
       "3   \\n**Ava Elizabeth Lee**\\n**Python Full Stack D...  Selected   \n",
       "4   \\n**Sophia Elizabeth Patel**\\n**Machine Learni...  Selected   \n",
       "..                                                ...       ...   \n",
       "95  \\n**Alexandra Paige Reynolds**\\n**Contact Info...  Selected   \n",
       "96  \\n**Gabriella Isabelle Rodriguez**\\n**Contact ...  Selected   \n",
       "97  \\n**Charlotte E. Brown**\\n**Contact Informatio...  Rejected   \n",
       "98  \\n**Liam Joseph Patel**\\n**Contact Information...  Selected   \n",
       "99  \\n**Maya Rachel Patel**\\n**Contact Information...  Selected   \n",
       "\n",
       "                                  Reason for decision  \\\n",
       "0   Demonstrated commitment to continuous learning...   \n",
       "1   Demonstrated commitment to continuous learning...   \n",
       "2   Experience with agile methodologies and projec...   \n",
       "3   Solid understanding of industry best practices...   \n",
       "4   Innovative thinking and a proactive approach t...   \n",
       "..                                                ...   \n",
       "95  Demonstrated strong leadership and teamwork sk...   \n",
       "96  Demonstrated commitment to continuous learning...   \n",
       "97  Inadequate experience with key technologies re...   \n",
       "98  Solid understanding of industry best practices...   \n",
       "99  Innovative thinking and a proactive approach t...   \n",
       "\n",
       "                                      Job Description  \n",
       "0   Implement RESTful APIs for seamless frontend-b...  \n",
       "1   Analyze complex datasets to generate actionabl...  \n",
       "2   Create intuitive user interfaces based on user...  \n",
       "3   Implement RESTful APIs for seamless frontend-b...  \n",
       "4    Optimize models for performance and scalability.  \n",
       "..                                                ...  \n",
       "95  Develop dashboards and reports to visualize ke...  \n",
       "96  Create intuitive user interfaces based on user...  \n",
       "97  Develop and deploy machine learning models for...  \n",
       "98  Monitor and manage cloud deployments to ensure...  \n",
       "99   Optimize models for performance and scalability.  \n",
       "\n",
       "[100 rows x 8 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
